### PR TITLE
New make build system. 

### PR DESCRIPTION
**Pull request by DanteCpp**
My suggestion is switching to the make build system, so that will be possible install the application directly from the last released's source code, with simple command well-knew to the unix users:

`make`

for compile, generate the jar and clean

`sudo make install`

for install the software into the system. 

About the developers, won't be big changes of the dev tools. 
In fact the make system just execs the scripts of the "old" developers tools, now moved into dev_tools/.

Compiling needs just 

`make compile`

instead of 

`./compile`

This approach makes the directory tree cleaner for a simple user which download the source just for install the application in his system. At the same time, it keeps simplicity of the developers' tools.

### CODE REVIEW

**Comment by DarwinNE** [comment]
Hi @DanteCpp,
  I like your proposal!

I think you can add other commits while I leave open this pull request (if not, tell me!).
Do not forget to read carefully and update the README file (paragraphs 2, 3.1 etc.). Be careful in cases such as paragraph 3.2: if you moved winbuild.bat you should specify there that it is in dev_tools.
Do not delete in the README a documentation concerning the scripts I wrote, but move the relevant information in a description of the dev-tools directory. Same for the static code checking data (PMD and Checkstyle).

I have now two questions: 
- I usually employ the "rebuild" script which does not appear in the makefile. Is that intentional? Probably because make is not expected to launch the program, but _please_ leave at least a way to easily rebuild everything from scratch and launch the program. I _really_ need that during the development without messing with dev_tools manually.
- in the launch scripts, you can pass some arguments to test the command line behavior of FidoCadJ without having to create a jar file. Can you find a way to maintain this way of doing things?

`./run -h`

Cheers,

D.

**Comment by DanteCpp** [comment]
Hi Davide,

> Is that intentional? 

No, it isn't. I just forgot that command. Given the simplicity of ./rebuild I decided to remove it and id implement its behavior, directly on the makefile.
So typing 

`make rebuild`

you get the same result as 

`make clean`
`make compile`
`make run`

sequentially typed. 

 

> Can you find a way to maintain this way of doing things?

Unfortunately the best thing, we may obtain is something like that

`make run ARGS="-h -t foo"`

I started to update the README, do you have suggestions about the location of the developers' tools description? And how mach deepen should be those information?

**Comment by DarwinNE** [comment]
Great stuff.

The README description of the dev-tools directory seems OK to me.
It seems to me that the README for the Android application cites one of the paragraph you renumbered. I am merging the pull request now, but can you please check that if you can?
Cross references are useful, yet they are a PITA sometimes :)

Cheers,

D.

**Comment by DarwinNE** [comment]
I tried the code and it works.
Maybe it would be nice if just writing "make" would be the same as "make compile", for example.

Cheers,
D.

**Pull request merged**
