### PR TITLE
Create MessagesBundle_el.properties

### PR DESCRIPTION
**Pull request by geogeo-gr**
Greek translation to v0.24.7

### CODE REVIEW

**Comment by DarwinNE** [comment]
Hi and thanks @geogeo-gr 

That's great work!!!

I am (slowly) working towards version 0.24.8, there are some additional resources with respect to v0.24.7:

`res_export=Set resolution in dpi
size_export=Set size in pixels`

Do you think you can add them so that I can merge with an up-to-date file?

Kind regards,
D.

**Comment by geogeo-gr** [comment]
Greek language file updated with new string
[FidoCadJ_el.zip](https://github.com/DarwinNE/FidoCadJ/files/3002200/FidoCadJ_el.zip)

**Comment by geogeo-gr** [comment]
Ok. Ready Greek file with new resources.
[FidoCadJ_el.zip](https://github.com/DarwinNE/FidoCadJ/files/3002215/FidoCadJ_el.zip)

**Comment by DarwinNE** [comment]
Merged.

**Pull request merged**
