### PR TITLE
Improved dev tools and fixed javadoc generating errors.

### PR DESCRIPTION
**Pull request by DanteCpp**
### Change log:

-  `make` works as `make compile`.
- fixed all doc generating errors, discussed in #35.
- improved the `dev_tools/cleanall` and `dev_tools/clean` scripts.

Remember do not use, or correctly escape the special characters `<>"'\&` in the comments.

### CODE REVIEW

**Comment by DarwinNE** [comment]
Nice work, @DanteCpp, thanks!

**Comment by DarwinNE** [comment]
Hi again, @DanteCpp,
  i ran some tests with Checkstyle.

Be careful about the line length and do not use tabs in the code or trailing spaces. Checkstyle complains about that. Have a look here:
https://github.com/DarwinNE/FidoCadJ/blob/506259b/dev_tools/fidocadj_check.txt
Can you please correct that?

Kind regards,
D.

**Comment by DanteCpp** [comment]
Hi @DarwinNE, 
it is pretty strange, because if you manually check some accused file, you can see it do not over length 80 characters.

Anyway you are right about the tabulations. 

What is the correct work flow for the checkstyle analysis? 

Cheers,
Dante.

**Comment by DarwinNE** [comment]
Hi @DanteCpp,
  I see that. Probably it is because Checkstyle considers that a single tab contains 8 spaces instead of 4. Problems of this kind should be avoided by avoiding tabs at all.

To employ checkstyle, you can download Checkstyle here:

[http://checkstyle.sourceforge.net](http://checkstyle.sourceforge.net)

then put the jar file somewhere in your disk.
Then, you employ the checkstyle script as follows:

[davidebucci@davide-bucci-portable]$ cd dev_tools/
```
[davidebucci@davide-bucci-portable]$ ./checkstyle.sh ~/CodeAnalysis/checkstyle/checkstyle-6.10-all.jar
Checkstyle results stored in fidocadj_check.txt
lines on fidocadj_check.txt
     805 fidocadj_check.txt
[davidebucci@davide-bucci-portable]$ 
```

Where the ~/CodeAnalysis/checkstyle/checkstyle-6.10-all.jar is the path where I put the Checkstyle jar file.

It is a tremendously useful and wonderful program.

Cheers,
D.

**Comment by DanteCpp** [comment]
Thanks, yes it is really a useful tool!

**Pull request merged**
