### PR TITLE
Added a download button on the index.html page. The button try to understand the user's OS and provide the right version of FidoCadJ, that's done by the JS code on the index.html page. The button style is defined on the CSS file

### PR DESCRIPTION
**Pull request by MigthyThor**
This is going to solve the #13 Issue

### CODE REVIEW

**Comment by DarwinNE** [comment]
Nice work!

**Comment by DarwinNE** [comment]
I am playing with the new download button. It seems to work (at least with MacOSX).
If I click on "I need another version of FidoCadJ.", should not direct me towards the "Download" page?

BTW, I think it would be able to write "I need another version of FidoCadJ" without the period, since it is a title, in my opinion.

**Comment by MigthyThor** [comment]
Oh sorry! I missed the link on the other version download page. Did you fix it? I left the # place-marker.

If you can't I'll do it. 

About the text and other stuff, you always can make improvement on my work if you think is better, I'll download your version of the code before starting another branch.

bye!

**Comment by DarwinNE** [comment]
Hi MigthyThor,
  for the moment, I am not planning to work on the website for a while, I am refactoring and cleaning the Java code, so if you want to do the corrections, go ahead.

Cheers,

D.

**Comment by MigthyThor** [comment]
It's a necessary correction about the link, so I'll do immediately.

**Pull request merged**
